### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by hacker1024** [felangel/stream_listener#3]
Are there any plans to support null safety in these packages?

**Comment by felangel** [comment]
Hi @hacker1024 👋
Thanks for opening an issue!

Yes, definitely! It just hasn’t been a top priority for me but I’m happy to prioritize it higher if it’s a blocker for you 👍

**Comment by hacker1024** [comment]
Thanks for the offer!
At the moment, as several other important packages still haven't migrated, I (and I suspect most others) am still running with sound null safety disabled, so this package isn't really a blocker - there's no pressure. Take your time.

**Comment by felangel** [comment]
Thanks to @lsaudon both packages have been migrated to null safety via #4 🎉
